# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fucked Up Guy
email: kkusumawathi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm fuckedupguy. and I'm gona post all my fucked up stories on this blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fuckedupguy.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  fuckedupguy

# Build settings
markdown: kramdown
permalink: /:title
